### ISSUE TITLE
Can not be installed

### ISSUE THREAD

**Issue by alireza-khabbazzadeh** [taylornetwork/username-suggester#1]
hi,
i can't install this package
laravel 9.16
i installed taylornetwork/laravel-username-generator

composer require taylornetwork/username-suggester

i get this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires taylornetwork/username-suggester ^0.1.0 -> satisfiable by taylornetwork/username-suggester[0.1].
    - taylornetwork/username-suggester 0.1 requires illuminate/support ^8.58 -> found illuminate/support[v8.58.0, ..., 8.x-dev] but these were not loaded, likely b
ecause it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require taylornetwork/username-suggester:*" to figure out if any v
ersion is installable, or "composer require taylornetwork/username-suggester:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by samyrataylor** [comment]
Hi @alireza-khabbazzadeh 

I've just updated the Laravel version requirements so you should be able to install it now.

**Comment by samyrataylor** [comment]
I'm assuming you were able to install it. I'm going to close this issue. If you have other problems feel free to open another.
